export const types = {
    ADDTODO: 'ADDTODO',
    REMOVETODO: 'REMOVETODO',
    UPDATETODO: 'UPDATETODO',
    FILTERTODO: 'FILTERTODO',
    TOGGLETODO: 'TOGGLETODO',
    TOGGLEEDIT: 'TOGGLEEDIT',
};
